# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Desktop/new_files_22-may/vehicle/vehicle_with_domain.cache/wt [current_project]
set_property parent.project_path D:/Desktop/new_files_22-may/vehicle/vehicle_with_domain.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib D:/Desktop/new_files_22-may/vehicle/vehicle_with_domain.srcs/sources_1/imports/vehicle/verilog_controller.v
synth_design -top DD -part xc7z010clg400-1 -mode out_of_context
write_checkpoint -noxdef DD.dcp
catch { report_utilization -file DD_utilization_synth.rpt -pb DD_utilization_synth.pb }
